# Generated by Django 3.2.9 on 2022-03-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0003_accountemailconfirmation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountemailconfirmation',
            name='slug',
        ),
    ]
