# Generated by Django 3.2.9 on 2021-11-13 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('reminder', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('WithOUt', 'without'), ('First', 'first'), ('Second', 'second'), ('Third', 'third')], max_length=10)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
