# Generated by Django 3.2.9 on 2023-06-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('first', 1), ('second', 2), ('third', 3)], max_length=10),
        ),
    ]
