# Generated by Django 3.2.9 on 2021-11-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='Tree',
            new_name='tree',
        ),
    ]
