# Generated by Django 3.2.9 on 2022-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('without', 0), ('first', 1), ('second', 2), ('third', 3)], max_length=10),
        ),
    ]
